"""Init migration

Revision ID: 9cc92b5c7e39
Revises: 
Create Date: 2026-03-10 23:17:56.485829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9cc92b5c7e39'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('deviceId', sa.String(), nullable=False),
    sa.Column('fileNames', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deviceId', 'fileNames', name='unique_attachment_constraint')
    )
    op.create_index('ix_attachment_tags', 'attachments', ['tags'], unique=False, postgresql_using='gin')
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'users', ['username'], unique=True)
    op.create_table('attachmentcreationtasks',
    sa.Column('attachment_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'DONE', 'FAILED', name='taskstatus'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attachmentcreationtasks')
    op.execute(sa.text('DROP TYPE taskstatus'))
    op.drop_index(op.f('ix_user_username'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_attachment_tags', table_name='attachments', postgresql_using='gin')
    op.drop_table('attachments')
    # ### end Alembic commands ###
